name: Extract POM metadata
description: "Extract POM metadata"

inputs:
  pomDir:
    description: pom.xml location
    required: true

outputs:
  appGroupId:
    description: ""
    value: ${{ steps.metadata.outputs.appGroupId }}
  appArtifactId:
    description: ""
    value: ${{ steps.metadata.outputs.appArtifactId }}
  appVersion:
    description: ""
    value: ${{ steps.metadata.outputs.appVersion }}
  appCommitId:
    description: ""
    value: ${{ steps.metadata.outputs.appCommitId }}

runs:
  using: "composite"

  steps:
    - name: Get application metadata from pom.xml
      id: metadata
      run: |
        export APP_GROUP_ID=$(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout)
        export APP_ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
        export APP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        export APP_COMMIT_ID=$(git rev-parse --short "$GITHUB_SHA")
        echo "::set-output name=appGroupId::$APP_GROUP_ID"
        echo "::set-output name=appArtifactId::$APP_ARTIFACT_ID"
        echo "::set-output name=appVersion::$APP_VERSION"
        echo "::set-output name=appCommitId::$APP_COMMIT_ID"
